---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'jkt-serverless-packages'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
